### ISSUE TITLE
Excessive valid email address checks being sent to Paystack?

### ISSUE THREAD

**Issue by iaremarkus** [a11rew/medusa-payment-paystack#99]
Hello :) 

Going through my logs, I found a session where THOUSANDS of these errors were logged - multiple checks per second.

What's the scenario where this would happen? Anything I should change on my end?

![pic-004501](https://github.com/a11rew/medusa-payment-paystack/assets/936966/02481c14-3111-4243-b70b-276d449c32d9)

**Comment by a11rew** [comment]
Hi, I took a look at your site from the url you shared in the last issue, your storefront is spamming createPaymentSession requests to your backend even before the user provides any information on the checkout page. That's why this is happening. 

![image](https://github.com/a11rew/medusa-payment-paystack/assets/87580113/c64f437d-fc8f-47e3-af52-ab53cfe3fa14)

This is most likely because of a bad useEffect in the storefront causing the `initPayment` method to be ran in a loop. You should fix the indefinite loop and for good measure only create payment sessions when you can confirm the user has provided an email (in addition to any other info your configured payment providers need).

**Comment by iaremarkus** [comment]
Thanks @a11rew . Super weird as this is the provided Storefront - I changed UI, but added no new functionality, so weird that this is the case.

I'll see if I can debug myself, or otherwise ping the the dev from MedusaJS
